##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## X|Y|Z & Dev
##
## Copyright Ⓒ Robert Mollentze, xyzand.dev
## 
## Licensing details can be found in the LICENSE file in the root directory.
## 
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: _service_interfaces
publish_to: none

## -----------------------------------------------------------------------------

environment:

  sdk: '>=3.0.0 <4.0.0'

## -----------------------------------------------------------------------------

dependencies:

  flutter:
    sdk: flutter

  _data:
    path: ../_data

  xyz_pod: ^0.20.0
  xyz_utils: ^0.47.0
    
  http: any

## -----------------------------------------------------------------------------

dev_dependencies:

  flutter_lints: any