##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## 🇽🇾🇿 & Dev
##
## Licencing details are in the LICENSE file in the root directory.
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: _service_interfaces
publish_to: none

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.3.1 <4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  flutter:
    sdk: flutter

  _data:
    path: ../_data

  xyz_gen_annotations: ^0.50.0
  xyz_pod: ^0.49.0
  xyz_utils: ^0.63.2

  equatable: any
  http: any
  meta: any

  file_picker: ^8.0.3

## -----------------------------------------------------------------------------

dependency_overrides:
  # TODO: Comment out these lines if you don't have these packages at their
  # respective paths. They are included for development purposes to allow
  # simultaneous work on this package and its dependencies.
  # xyz_gen_annotations:
  #   path: ../../xyz_gen/xyz_gen_annotations
  # xyz_pod:
  #   path: ../../xyz_pod
  # xyz_utils:
  #   path: ../../xyz_utils

## -----------------------------------------------------------------------------

dev_dependencies:
  flutter_lints: any
